### ISSUE TITLE
Assertions fail but pass in the SoapUI application

### ISSUE THREAD

**Issue by g1ps** [creising/soapui-gradle-plugin#3]
Hi,

Please see [https://github.com/byte-shifter-ltd/soapui-gradle-plugin/issues/15](https://github.com/byte-shifter-ltd/soapui-gradle-plugin/issues/15), repeated here for convenience. The same occurs with this plugin, not surprisingly. Any assistance you can provide will be appreciated.

>I'm trying to run existing tests using Gradle and your plugin. We have a custom namespace and a bunch of tests that run regularly and pass. When I try to run them through the plugin, the test is able to authenticate with the service and retrieve a valid response but the assertions fail. The assertions pass using SoapUI 4.5.2 and 5.3.0. The plugin uses 5.0.1. I haven't been able to test whether that's a factor.
>
>Here's an extract from the response

    <sample xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="<custom ns>">
      <id>2</id>
      <material_alias>Cold-Cold</material_alias>
      <material_id>23</material_id>
      <name>CT-000000023-0</name>
      <original_experiment_id>1</original_experiment_id>
      <priority>3</priority>
      <hazards>
        ...

>and here are two of the assertions

    <con:assertion type="XPath Match" name="Sample exists">
              <con:configuration>
                <path>declare namespace ns1='<custom ns>';
    exists(/ns1:sample)</path>
                <content>true</content>
                <allowWildcards>false</allowWildcards>
                <ignoreNamspaceDifferences>false</ignoreNamspaceDifferences>
                <ignoreComments>false</ignoreComments>
              </con:configuration>
            </con:assertion>
            <con:assertion type="XPath Match" name="Assert id">
              <con:configuration>
                <path>declare namespace ns1='<custom ns>;
    /ns1:sample/ns1:id</path>
                <content>2</content>
                <allowWildcards>false</allowWildcards>
                <ignoreNamspaceDifferences>false</ignoreNamspaceDifferences>
                <ignoreComments>false</ignoreComments>
              </con:configuration>
            </con:assertion>
>
>and here are the results
>
    ----------------- Messages ------------------------------
    [Sample exists] XPathContains assertion failed for path [declare namespace ns1='<custom ns>';
    exists(/ns1:sample)] : RuntimeException: Trying XBeans path engine... Trying XQRL..
    . Trying XDK... Trying delegated path engine... FAILED on declare namespace ns1='<custom ns>';
    exists(/ns1:sample)
    [Assert id] XPathContains assertion failed for path [declare namespace ns1='<custom ns>'; 
    /ns1:sample/ns1:id] : RuntimeException: Trying XBeans path engine... Trying XQRL...
    Trying XDK... Trying delegated path engine... FAILED on declare namespace ns1='<custom ns>';
    /ns1:sample/ns1:id
>
>Everything I've read says that the first slash before ns1 should be doubled. I've tried that both in Gradle and SoapUI and it hasn't changed things. I've also tried all sorts of variations, playing with namespaces, adding new assertions, etc. I can add new ones that pass in the app. I've been unable to add a single assertion that works in Gradle. I haven't been able to find where the plugin stores it's soapui jar to see if updating it would help.
>
>I can't see any reason why these assertions should fail and, given that they pass in two versions of SoapUI, it does look like there's a bug somewhere. This is a blocking issue for me so any help will be appreciated.
>
>Thanks.

**Comment by creising** [comment]
Hi g1ps. Right now things are a little crazy for me, but if you want to experiment with the version is uses for soap-ui I just created a branch (version) that depends on soap-ui 5.2.1 if you wanted to try that. Sorry I do not have more time to look into this.

**Comment by g1ps** [comment]
Hi,

That's great, thanks. I will certainly try it. I'll try and do that today but it might take longer.

Cheers.

**Comment by g1ps** [comment]
It did take longer. Today might be the day. :-)

**Update**: OK, maybe not. I don't know what to do with that. I'm not set up to do Java compilation. I'd need a binary release or some instructions which explain how to make it work with Gradle.

Thanks.

**Comment by creising** [comment]
Let's try this. I uploaded a new [version](https://plugins.gradle.org/plugin/org.urbanbyte.soapui/0.4.4-beta) of the plugin which you can just reference in your build.gradle. I tested this on an simple [example](https://github.com/creising/soapui-plugin-example-) project i have to see if the tests run (using the soaptest target). It appears they do. I did see, however, that SOAP-UI is complaining about a missing class. I did some quick searches and it appears this is a known issue with 5.2. As far as I can tell the tests still run. I can try to chase it down more when I have sometime. Until then, hopefully this will make it easy for you to see if this helps without having to worry about building anything locally.

**Comment by g1ps** [comment]
Hi,

Many thanks. Unfortunately the information provided [here](https://plugins.gradle.org/plugin/org.urbanbyte.soapui/0.4.4-beta) doesn't work. The plugin fails looking for SoapUI. I had to use the long version and add

     maven { url "http://www.soapui.org/repository/maven2/" }

as per byteshifter's version, to get it to work. I'm now testing the assertions.

Cheers.

**Comment by g1ps** [comment]
Thanks again for the change. The assertions still fail out of the box. Myself and two other devs have spent some more time on it and we can't see why they fail. The test returns valid XML, shows it to us and then says that the assertion failed. The tests still pass in various versions of SOAP UI. I'm not sure what else we can do. When I get some more time I might try setting up a new, clean test from scratch and see if I can get that to work with the plugin. It's not beyond the realms of possibility that it's something in our tests but we're stumped as to what that could be.

Cheers.

**Comment by g1ps** [comment]
Some additional info. When initially run, the plugin reports this:

```
Missing folder [E:\Utilities\Programming\Automation\QA\AutoOps\ext] for external
 libraries
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethod
Factory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:377)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFac
tory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:377)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethod
Factory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:377)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFac
tory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:377)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethod
Factory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:377)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFac
tory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:377)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethod
Factory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFac
tory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethod
Factory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
DiscoveryMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFac
tory], see error log for details
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
java.lang.ClassNotFoundException: com.eviware.soapui.plugins.auto.factories.Auto
ImportMethodFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.eviware.soapui.plugins.LoaderBase.loadAutoFactories(LoaderBase.ja
va:96)
        at com.eviware.soapui.plugins.LoaderBase.loadFactories(LoaderBase.java:6
4)
        at com.eviware.soapui.plugins.PluginLoader.loadPluginFactories(PluginLoa
der.java:129)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
92)
        at com.eviware.soapui.plugins.PluginLoader.loadPlugin(PluginLoader.java:
42)
        at com.eviware.soapui.plugins.PluginManager.doInstallPlugin(PluginManage
r.java:136)
        at com.eviware.soapui.plugins.PluginManager.access$600(PluginManager.jav
a:38)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.computeSeque
ntially(PluginManager.java:415)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:372)
        at com.eviware.soapui.plugins.PluginManager$LoadPluginsTask.compute(Plug
inManager.java:360)
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)

```
Creating a directory called `ext` stops this occurring but could be hiding a problem.

We also found these:
[
http://stackoverflow.com/questions/9827984/xpath-validation-fails-on-automated-test-with-maven-soap-ui-plugin](
http://stackoverflow.com/questions/9827984/xpath-validation-fails-on-automated-test-with-maven-soap-ui-plugin
)
[https://community.smartbear.com/t5/SoapUI-Open-Source/XPath-assertions-always-fail-with-maven-plugin/td-p/21338](https://community.smartbear.com/t5/SoapUI-Open-Source/XPath-assertions-always-fail-with-maven-plugin/td-p/21338)

which, although old, sound much the same. They both point to dependency issues so I wonder if we're having a similar problem.
